// Named repo icons Conductor stores in `repos.icon` (e.g. `book`, `monitor`) are
// Lucide icon names. We map the ones a repo icon-picker plausibly offers to their
// statically-imported components — tree-shaken, so only these ship in the bundle.
// (Rendering by arbitrary name via `lucide-react/dynamic` would code-split all
// ~1900 icons into separate chunks and balloon the PWA precache.)
//
// The set was validated against the installed lucide-react version; an unmapped
// name simply falls back to the letter monogram. Extend as new names appear.
import type { LucideIcon } from 'lucide-react'
import {
	Activity,
	Anchor,
	Apple,
	Atom,
	Award,
	Banknote,
	Battery,
	Beer,
	Bell,
	Bike,
	Bird,
	Bluetooth,
	Book,
	Bookmark,
	BookOpen,
	Bot,
	Box,
	Brain,
	Briefcase,
	Brush,
	Bug,
	BugPlay,
	Building,
	Building2,
	Cake,
	Calendar,
	Camera,
	Car,
	Carrot,
	Cat,
	ChartBar,
	ChartLine,
	ChartPie,
	Clapperboard,
	Clock,
	Cloud,
	Code,
	CodeXml,
	Coffee,
	Cog,
	Compass,
	Cpu,
	CreditCard,
	Crown,
	Database,
	Dna,
	Dog,
	DollarSign,
	Dumbbell,
	Egg,
	Factory,
	Feather,
	File,
	FileCode,
	Film,
	Fish,
	Flag,
	Flame,
	FlaskConical,
	Folder,
	Gamepad2,
	Gem,
	Gift,
	GitBranch,
	Github,
	Glasses,
	Globe,
	GraduationCap,
	Grid3x3,
	Hammer,
	Headphones,
	Heart,
	HeartPulse,
	House,
	Image,
	Key,
	Laptop,
	Layers,
	LayoutGrid,
	Leaf,
	Lightbulb,
	Link,
	Lock,
	Mail,
	Map as MapIcon,
	MapPin,
	Martini,
	Medal,
	MessageCircle,
	MessageSquare,
	Mic,
	Microscope,
	Monitor,
	Moon,
	Music,
	Orbit,
	Package,
	Paintbrush,
	Paperclip,
	PawPrint,
	Pen,
	Pencil,
	Phone,
	Pill,
	Pipette,
	Pizza,
	Plane,
	Plug,
	Power,
	Puzzle,
	Rabbit,
	Radio,
	Rocket,
	Ruler,
	Salad,
	Satellite,
	Scissors,
	Server,
	Settings,
	Shell,
	Shield,
	Ship,
	ShoppingBag,
	ShoppingCart,
	Smartphone,
	Snail,
	Soup,
	Sparkles,
	Sprout,
	Star,
	Stethoscope,
	Store,
	Sun,
	Tag,
	Tags,
	Target,
	Telescope,
	Terminal,
	Ticket,
	TrainFront,
	TreePine,
	TrendingUp,
	Trophy,
	Turtle,
	User,
	Users,
	Utensils,
	Video,
	Wallet,
	Wand2,
	WandSparkles,
	Warehouse,
	Wheat,
	Wifi,
	Wine,
	Wrench,
	Zap
} from 'lucide-react'

export const LUCIDE_ICONS: Record<string, LucideIcon> = {
	activity: Activity,
	anchor: Anchor,
	apple: Apple,
	atom: Atom,
	award: Award,
	banknote: Banknote,
	battery: Battery,
	beer: Beer,
	bell: Bell,
	bike: Bike,
	bird: Bird,
	bluetooth: Bluetooth,
	book: Book,
	'book-open': BookOpen,
	bookmark: Bookmark,
	bot: Bot,
	box: Box,
	brain: Brain,
	briefcase: Briefcase,
	brush: Brush,
	bug: Bug,
	'bug-play': BugPlay,
	building: Building,
	'building-2': Building2,
	cake: Cake,
	calendar: Calendar,
	camera: Camera,
	car: Car,
	carrot: Carrot,
	cat: Cat,
	'chart-bar': ChartBar,
	'chart-line': ChartLine,
	'chart-pie': ChartPie,
	clapperboard: Clapperboard,
	clock: Clock,
	cloud: Cloud,
	code: Code,
	'code-xml': CodeXml,
	coffee: Coffee,
	cog: Cog,
	compass: Compass,
	cpu: Cpu,
	'credit-card': CreditCard,
	crown: Crown,
	database: Database,
	dna: Dna,
	dog: Dog,
	'dollar-sign': DollarSign,
	dumbbell: Dumbbell,
	egg: Egg,
	factory: Factory,
	feather: Feather,
	file: File,
	'file-code': FileCode,
	film: Film,
	fish: Fish,
	flag: Flag,
	flame: Flame,
	'flask-conical': FlaskConical,
	folder: Folder,
	'gamepad-2': Gamepad2,
	gem: Gem,
	gift: Gift,
	'git-branch': GitBranch,
	github: Github,
	glasses: Glasses,
	globe: Globe,
	'graduation-cap': GraduationCap,
	'grid-3x3': Grid3x3,
	hammer: Hammer,
	headphones: Headphones,
	heart: Heart,
	'heart-pulse': HeartPulse,
	house: House,
	image: Image,
	key: Key,
	laptop: Laptop,
	'layout-grid': LayoutGrid,
	layers: Layers,
	leaf: Leaf,
	lightbulb: Lightbulb,
	link: Link,
	lock: Lock,
	mail: Mail,
	map: MapIcon,
	'map-pin': MapPin,
	martini: Martini,
	medal: Medal,
	'message-circle': MessageCircle,
	'message-square': MessageSquare,
	mic: Mic,
	microscope: Microscope,
	monitor: Monitor,
	moon: Moon,
	music: Music,
	orbit: Orbit,
	package: Package,
	paintbrush: Paintbrush,
	paperclip: Paperclip,
	'paw-print': PawPrint,
	pen: Pen,
	pencil: Pencil,
	phone: Phone,
	pill: Pill,
	pipette: Pipette,
	pizza: Pizza,
	plane: Plane,
	plug: Plug,
	power: Power,
	puzzle: Puzzle,
	rabbit: Rabbit,
	radio: Radio,
	rocket: Rocket,
	ruler: Ruler,
	salad: Salad,
	satellite: Satellite,
	scissors: Scissors,
	server: Server,
	settings: Settings,
	shell: Shell,
	shield: Shield,
	ship: Ship,
	'shopping-bag': ShoppingBag,
	'shopping-cart': ShoppingCart,
	smartphone: Smartphone,
	snail: Snail,
	soup: Soup,
	sparkles: Sparkles,
	sprout: Sprout,
	star: Star,
	stethoscope: Stethoscope,
	store: Store,
	sun: Sun,
	tag: Tag,
	tags: Tags,
	target: Target,
	telescope: Telescope,
	terminal: Terminal,
	ticket: Ticket,
	'train-front': TrainFront,
	'tree-pine': TreePine,
	'trending-up': TrendingUp,
	trophy: Trophy,
	turtle: Turtle,
	user: User,
	users: Users,
	utensils: Utensils,
	video: Video,
	wallet: Wallet,
	'wand-2': Wand2,
	'wand-sparkles': WandSparkles,
	warehouse: Warehouse,
	wheat: Wheat,
	wifi: Wifi,
	wine: Wine,
	wrench: Wrench,
	zap: Zap
}
